from src.utils import get_project_root
from src.constants import (
    DATA_DIR,
    RAW_DATA_DIR,
    INTERIM_DATA_DIR,
    PROCESSED_DATA_DIR,
    EXTERNAL_DATA_DIR,
    MODELS_DIR,
    REPORTS_DIR,
    FIGURES_DIR,
    LOG_DIR,
    INGESTION_COMP,
    YAML_DIR,
    COMPONENT_PARAM_FILE_NAME,
    SCHEMA_PARAM_FILE_NAME,
    VALIDATION_COMP,
)

PROJ_ROOT = get_project_root()

# Base paths
DATA_DIR_PATH = PROJ_ROOT / DATA_DIR
MODELS_DIR_PATH = PROJ_ROOT / MODELS_DIR
REPORTS_DIR_PATH = PROJ_ROOT / REPORTS_DIR

# Data subpaths
RAW_DATA_DIR_PATH = DATA_DIR_PATH / RAW_DATA_DIR
INTERIM_DATA_DIR_PATH = DATA_DIR_PATH / INTERIM_DATA_DIR
PROCESSED_DATA_DIR_PATH = DATA_DIR_PATH / PROCESSED_DATA_DIR
EXTERNAL_DATA_DIR_PATH = DATA_DIR_PATH / EXTERNAL_DATA_DIR

# Report subpaths
FIGURES_DIR_PATH = REPORTS_DIR_PATH / FIGURES_DIR

# Logs Directory

LOG_DIR_PATH = PROJ_ROOT / LOG_DIR
INGESTION_LOG_DIR_PATH = LOG_DIR_PATH / INGESTION_COMP


# YAML CONFIG's

YAML_DIR_PATH = PROJ_ROOT / YAML_DIR
COMPONENT_PARAM_FILE_PATH = YAML_DIR_PATH / COMPONENT_PARAM_FILE_NAME
SCHEMA_PARAM_FILE_PATH = YAML_DIR_PATH / SCHEMA_PARAM_FILE_NAME


# Validation Configs
VALIDATION_LOG_DIR_PATH = LOG_DIR_PATH / VALIDATION_COMP
VALIDATION_REPORT_DIR_PATH = REPORTS_DIR_PATH / VALIDATION_COMP
