ingestion:

  foreign_key: "TransactionID"

  target_column: "isFraud"

  required_columns:
    - TransactionID
    - isFraud
    - TransactionDT
    - TransactionAmt
    - ProductCD

  expected_dtypes:
    TransactionID: int64
    isFraud: int8
    TransactionDT: int64
    TransactionAmt: float32
